sudo: required 
services: 
    - docker 

before_install: 
    - docker build -t abhisandireddy/docker-react -f Dockerfile.dev . 

script: 
    - docker run abhisandireddy/docker-react npm run test -- --coverage